### ISSUE TITLE
File upload in LoopBack 4

### ISSUE THREAD

**Issue by initfusion** [loopbackio/loopback.io#791] opened 2019-01-05 13:44 UTC
Hi,

I am new to LoopBack, How to upload file in spacific foler in LoopBack 4.

Thanks.

**Comment by dhmlau** [comment] 2019-01-15 19:21
@initfusion , you might want to check out the following articles:
https://loopback.io/doc/en/lb4/Parsing-requests.html
https://strongloop.com/strongblog/the-journey-to-extensible-request-body-parsing/

Hope it helps.

**Comment by dhmlau** [comment] 2019-02-08 23:00
@initfusion , i'd like to continue the discussion about file upload in this issue: https://github.com/strongloop/loopback-next/issues/1873.  As a result, closing this issue as duplicate of https://github.com/strongloop/loopback-next/issues/1873. Thanks.

**Closed as completed by dhmlau** 2019-02-08 23:00 UTC
