### ISSUE TITLE
Application generator --explorer switch behaviour inconsistency

### ISSUE THREAD

**Issue by LubosBaja** [loopbackio/loopback.io#553] opened 2017-11-29 16:19 UTC
## URL of the page 
http://loopback.io/doc/en/lb3/Application-generator
http://loopback.io/doc/en/lb3/Create-a-simple-API.html

## Nature of the issue 
I am new to loopback, trying to follow chapter Getting started with Loopback 3.0 I have found the inconsistency in documentation or behaviour of application generator.
It is stated that apic loopback command creates application with API explorer. But I have to explicitly run command apic loopback --explorer to have the explorer included. So there is either mistake in documentation or behaviour of default --explorer switch.  

## Expected behavior
Either correct the statement that --explorer parameter is true as a default and state the correct application command in Creating a simple API (with --explorer stated)
Or fix the behaviour of --explorer parameter

What did you expect to happen?

## Actual behavior

What actually happenend, with steps to reproduce (if applicable).

## Suggested resolution

How do you think this should be resolved (optional).

**Comment by bschrammIBM** [comment] 2017-11-30 22:09
Hi, thank you for pointing this out. I will ask the team and get a resolution within a few days.

**Comment by dhmlau** [comment] 2017-12-01 15:24
@LubosBaja, the expected behavior is:
- if `lb [app] [options] [<name>]` is used, API explorer will be created by default
- if `apic loopback --type api [options]` is used, API explorer will *not* be created by default

I'll submit a PR to clarify this in the documentation.  Thanks for reporting this.

**Comment by bschrammIBM** [comment] 2017-12-01 20:02
Closing because the docs have been updated per docs: clarify API Explorer default #557

**Closed as completed by bschrammIBM** 2017-12-01 20:02 UTC
Labels: team-apex
