### ISSUE TITLE
operation hooks info not true

### ISSUE THREAD

**Issue by mamartins** [loopbackio/loopback.io#390] opened 2017-06-01 10:48 UTC
## URL of the page 

https://loopback.io/doc/en/lb2/Embedded-models-and-relations.html

## Nature of the issue 

The note about the operation hooks at least for the EmbedsMany relation is wrong. The hook 'before save' is not called for the embedded model when a parent one is created.

## Expected behavior

expected that a before save was called in the embedded model when a parent is created

## Actual behavior

the hook is not called

## Suggested resolution

update text or fix bug

**Comment by crandmck** [comment] 2017-06-02 16:54
@strongloop/sq-lb-asteroid 

Can someone pls determine whether:

- This is a doc issue, and embedsMany does not support op hooks on the embedded model.  If so, I'll updat docs accordingly.
- This is a bug and the op hook is not being called but should be.  If so, we should move this to another repo since it's not a doc issue.  We can add a link in doc to the issue until its resolved.
- It actually works, and we have a test case demonstrating it.

**Comment by crandmck** [comment] 2017-06-02 17:58
@ssh24 Here is my fork with the test case: https://github.com/crandmck/loopback-example-relations

I added `before save` hook in two places, and both seem to be called when the models are created:
- Boot script [z-customer-emails.js](https://github.com/crandmck/loopback-example-relations/blob/master/server/boot/z-customer-emails.js)
- Model JS file [email-address.js](https://github.com/crandmck/loopback-example-relations/blob/master/common/models/email-address.js)

**Comment by ssh24** [comment] 2017-06-02 18:06
Hi @mamartins. Could you please provide a breakdown of the steps you took to reproduce the issue you are facing? It will be helpful for us trying to reproduce and also see what you are doing (right/wrong).

**Comment by crandmck** [comment] 2017-06-07 20:28
@mamartins If we can't get a test case to reproduce your problem, then we'll close this issue.

**Closed as completed** 2017-06-13 23:41 UTC
